### ISSUE TITLE
Tab to select value in 2.1.4 version

### ISSUE THREAD

**Issue by shubhjn27** [shentao/vue-multiselect#1036] opened 2019-07-18 04:46 UTC
I want to select the value on tab key press. So that when the drop down closes, whichever is the value to which we scrolled to is selected. And then move to next control
It was working in v1.1.3 but not in 2.1.4

**Comment by shubhjn27** [comment] 2019-07-19 17:49
Any update on the same?

**Comment by monas** [comment] 2019-07-26 12:00
I almost found a way around for this use case by combining @open and @close events plus some local variable to store user input. If I could get some access to the pointer data property that would be quite good solution. But now I can not select anything from the existing items, just to insert new one by what the user is typed. One single property exposition or event for pointer change would solve this very nicely.

**Comment by monas** [comment] 2019-07-26 12:45
Here is how my workaround looks like in code:

```
<div @mouseleave="usingArrows = false">
	<vue-multiselect
		ref="myMultiselect"
		v-model="selectedItems"
		:options="optionsList"
		@keyup.native.down="keyArrowDown"
		@keyup.native.up="keyArrowUp"
		@open="autocompleteOpened"
		@close="autocompleteClosed"></vue-autocomplete>
</div>
```

Script part:
```
data() {
		return {
			// ...
			userInput: '',
			usingArrows: false
		};
	},

methods: {
		autocompleteOpened(id) {
			this.userInput = '';
			this.usingArrows = false;
		},
		autocompleteClosed(value, id) {
			if (this.userInput !== '' && !this.usingArrows) {
				this.addItems(this.userInput);
			}

			let targetItem = this.optionsList[this.$refs.myMultiselect.pointer];
			if (this.usingArrows === true && targetItem !== undefined 
				&& !targetItem.$isDisabled && !targetItem.isSeperator) {

				this.selectedItems.push(targetItem);
				this.$refs.myMultiselect.pointer = 0;

				this.$emit("input", this.selectedItems);
				this.usingArrows = false;
			}
		},
		keyArrowUp(e) {
			this.usingArrows = true;
		},
		keyArrowDown(e) {
			this.usingArrows = true;
		},
}
```

I skipped not meaningful parts, but the approach is like this.

**Comment by ipetrov87** [comment] 2019-08-08 06:22
If this was native functionality, this will be the what i am searching for.

**Comment by lorado** [comment] 2019-09-10 13:54
There are actually 2 PRs that implement this behaviour... This library seems to be not active developed... =(

**Comment by Arns** [comment] 2023-03-29 14:30
I'm also cannot specify an option that selects the option on tab.. +1

**Comment by Arns** [comment] 2023-03-29 14:34
Duplicate of #612, actually. @shentao mentioned that this is fixed in Version 3 and doesn't seem likely the PR will be merged for V2.

**Closed** 2023-04-12 12:43 UTC
