### ISSUE TITLE
[Bug] Cannot Shift+Tab out of searchable multiselect

### ISSUE THREAD

**Issue by justrhysism** [shentao/vue-multiselect#411] opened 2017-07-03 05:49 UTC
Fiddle: https://jsfiddle.net/justrhysism/rrh1ddqL/1/

Tabbing forwards works as expected. Shift-tabbing backwards is being prevented.

_Note: This bug doesn't exist in beta.15 as I had to update the JSFiddle script source to the latest to demo the issue._

Putting the major accessibility issues aside - many people (especially devs) navigate forms using [Tab] and [Shift+Tab] so this regression is a deal-breaker.

**Comment by shentao** [comment] 2017-07-03 09:30
Hey! Must have been a regression – it should have worked as before. Will fix in the coming days. Thanks! :)

**Comment by justrhysism** [comment] 2017-07-03 12:23
Awesome, thanks @shentao!

**Comment by hsnali** [comment] 2017-09-20 05:18
Hi @shentao, any progress on this one? 

Not being able to Shift + Tab out of multiselect is a real accessibility killer.

Love your work otherwise.

**Comment by shentao** [comment] 2017-09-20 09:10
Sorry, was very busy in the recent weeks. Planning to do a massive bugfixing this weekend so expect a release.

**Comment by skegel13** [comment] 2017-09-29 15:21
I am using Vue 2.4.4 and Vue Multiselect 2.0.3 and I still have the issue when searching is enabled. Tab will not select an item and shift+tab will not go back to the previous input. Everything seems to be working properly if searching is disabled.

**Comment by havgry** [comment] 2017-09-30 15:02
It's a huge issue in terms of accessibility and it's practically preventing me from using the `searchable` feature alltogether. I've submitted a PR.

**Comment by kanapka94** [comment] 2018-06-21 15:00
This issue still exists :(

**Comment by priyankamantala** [comment] 2018-06-25 09:00
Issue exists if multiselect is searchable then tabindex does not work

I m confused how it is working on this link -  https://jsfiddle.net/7ma9xuvp/6/
because its not working for me..

**Comment by NailsonCodens** [comment] 2018-07-20 18:37
the problem continues, killing the usability, did anyone find any solution? The multi-select owner does not seem to care much about this tab problem.

**Comment by jinfeicheng** [comment] 2018-11-27 17:39
he problem continues, killing the usability, did anyone find any solution?

**Comment by vadym1930** [comment] 2020-05-10 13:44
Was able to make this done in a dirty hacky way. Version: `"vue-multiselect": "2.1.0"`.
Grabbed this trick from https://github.com/shentao/vue-multiselect/issues/401#issuecomment-425582096 and added more.
```
mounted () {
     this.$refs.typeahead.$el.setAttribute('tabindex', 0);
     this.$refs.typeahead.$el.addEventListener('keydown', this.addShiftTabBehavior);
},
```
```
beforeDestroy() {
    this.$refs.typeahead.$el.removeEventListener('keydown', this.addShiftTabBehavior);
},
```
```
// ashamed code goes here
/**
 * Enables shift+tab navigation
 * @param e {MouseEvent}
 * @returns void
 */
addShiftTabBehavior(e) {
    if(e.shiftKey && e.keyCode == 9) {
        this.$refs.typeahead.$el.setAttribute('tabindex', -1);
    }

    setTimeout(() => {
        this.$refs.typeahead.$el.setAttribute('tabindex', 0);
    }, 10);
},
/**
 * Gets focus after option selected back.
 * @returns void
 */
onSelected () {
    this.$nextTick(() => this.$refs.typeahead.$el.focus());
}
```

**Comment by leeniu** [comment] 2020-05-11 15:56
Hey @vadym1930, the issue is fixed in the latest version 2.1.6

JSFiddle for reference: https://jsfiddle.net/leeniu/bf1va7ks/

**Closed by leeniu** 2020-05-11 15:56 UTC
Labels: bug
