### ISSUE TITLE
Adding tag with tab doesn't work after update

### ISSUE THREAD

**Issue by FabioOliveira1** [shentao/vue-multiselect#612] opened 2017-12-18 14:10 UTC
I've noticed that tab key isn't adding a new tag after updating vue-multiselect from 2.0.0-beta.15 to 2.0.8 (also happens with 2.0.1).

https://jsfiddle.net/foliveira151/jqofkzxc/258/#&togetherjs=FMcyMSMGAg

https://giphy.com/gifs/test-coding-vuejs-l4EoYp7bW15givQu4/fullscreen

**Comment by galenmaly** [comment] 2018-02-23 19:27
It looks like this behavior was changed in the following two commits:

First, the tab event listener was removed:
https://github.com/shentao/vue-multiselect/commit/41fc501e1e572d6c80451788743a6b41520a4454#diff-f0fe4bcbb4c9df5319d483db4c27ee58L48

Also, later, a dirty check was added that didn't accommodate taggable/searchable multiselects:
https://github.com/shentao/vue-multiselect/pull/430/files

I'm assuming that both of these were unintentional.

I've prepared a pull request reinstating the behavior of selecting with tab: https://github.com/shentao/vue-multiselect/pull/654

**Comment by markokeeffe** [comment] 2018-05-03 04:05
@shentao What are the chances this can be merged? Lack of tab in/out support is pretty disappointing 😕

**Comment by akoury** [comment] 2018-07-30 16:51
@shentao This issue was closed automatically, however it still remains and has a working fix that has not been merged, is there a way to reopen it so that the issue is not forgotten?

**Closed** 2018-09-05 18:06 UTC
Labels: wontfix

**Comment by akoury** [comment] 2018-09-06 03:06
@shentao This issue was closed automatically once again, however it still remains and has a working fix that has not been merged, is there a way to reopen it so that the issue is not forgotten?

**Comment by akoury** [comment] 2018-09-06 12:30
Hey @shentao dont be sorry! Remember you dont owe us anything, you've done more than enough with this great package, the only reason I commented was because I did not want the issue to be forgotten if it was closed, that way, one day if you have the time, you will be able to merge it (which I know is not easy because it can break other stuff), and if not then dont stress about it!

Thanks again

**Comment by shentao** [comment] 2018-09-06 13:16
It’s not forgotten. Actually, this is fixed in v3 that I try to finish in my free time. It’s just hard to do both – fix all the issues with v2 (since there will always be new) and work on v3. Hopefully, I will get some free time soon to work on the library. I would also welcome contributors that could take some of the weight from me by helping to fix the current master branch so we can do a release.
