### ISSUE TITLE
Prevent selecting any items when using single select (object)

### ISSUE THREAD

**Issue by masoud86** [shentao/vue-multiselect#1484] opened 2021-09-22 06:11 UTC
I'm using Vue-multiselect 2.1.4

It works like a charm when I use single select with array options. But in case of using single select with array of objects, all items are green and they are not selectable! (They have "is-selected" class)

To clarify the problem, I used the sample code from the project website and replace the options with my data.

![vue-multiselect-problem](https://user-images.githubusercontent.com/4735034/134291763-a0303b22-8252-4790-beef-cb677fa537fc.png)

    <multiselect v-model="value" deselect-label="Can't remove this value"
        track-by="name" label="name" placeholder="Select one"
        :options="options" :searchable="false" :allow-empty="false">
        <template slot="singleLabel" slot-scope="{ option }">
            <strong>{{ option.name }}</strong> is written in
            <strong>  {{ option.language }}</strong>
        </template>
    </multiselect>

----------

    const config = {
        data() {
            return {
                value: null,
                options: []
            }
        },
        async mounted() {
            await this.getTerminals();
        },
        methods: {
            async getTerminals() {
                await window.axios.get("/api/Operation/GetTerminals")
                    .then(resp => {
                        this.$data.options = resp.data;
                    })
                    .catch(err => {
                        console.error(err);
                    });
                },
        }
    };
    const app = Vue.createApp(config);
    app.component('Multiselect', VueformMultiselect);
    app.mount('#app');

**Comment by harshuchilzy** [comment] 2022-02-13 07:28
Same issue here.. Anybody with a solution?

**Comment by Momenoor** [comment] 2022-09-18 20:21
The same here, Any solution??

**Comment by akki-jat** [comment] 2022-10-27 16:43
@masoud86 Unable to reproduce this in latest version. Please provide reproduction repo.

**Comment by PH-Vieira** [comment] 2023-12-01 13:18
I have the same problem

**Comment by mattelen** [comment] 2024-12-31 11:47
Closing due to unable to reproduce, as well as it being for an older version.

**Closed by mattelen** 2024-12-31 11:47 UTC
Labels: needs repro
