### ISSUE TITLE
Tags appear in lowercase instead of as typed

### ISSUE THREAD

**Issue by snocorp** [shentao/vue-multiselect#560] opened 2017-11-02 04:13 UTC
JS Fiddle: https://jsfiddle.net/c86n383x/

Steps:
1. Enter a new tag with at least one capital letter (e.g. Vuex)

Expected: New tag appears exactly as typed
Actual: New tag appears in lowercase

The issue appears to have been introduced in the following commit: https://github.com/monterail/vue-multiselect/commit/42b18cff4e31734759b0c07a66d9ecd91d135939#diff-6b5af0f1e9c993645e63370d4087a280R317

It seems like it was intentional to change the label to use `normalizedSearch` but I'm not sure if the side-effect of only allowing lowercase tags was also intentional.

**Comment by faasie** [comment] 2017-11-03 02:11
I'm seeing this as well. Would like to see the ability to have the expected "appear as typed" instead of always lowercase.

**Comment by shentao** [comment] 2017-11-06 10:20
That’s a bug – it should only be lowercased for within the search. It should not mutate anything. My bad!

**Comment by snocorp** [comment] 2017-11-08 03:04
@shentao Is the intention of https://github.com/monterail/vue-multiselect/blob/master/src/multiselectMixin.js#L327 to ensure a tag is only added once, no matter the case? I'm trying to work on a PR for this.

**Comment by rickbolton** [comment] 2017-11-15 20:41
@snocorp I've just added a PR to fix this so hopefully will get merged 👍 - https://github.com/monterail/vue-multiselect/pull/588

**Comment by snocorp** [comment] 2017-11-16 03:25
The fix is relatively simple but how to fix it depends on the intent behind line 327 as I linked above. Changing the labels to keep their case will break the `isExistingOption` search as it works when all tags are in lowercase.

**Comment by rickbolton** [comment] 2017-11-17 13:29
@shentao can we bump this fix please? Understand that you may be busy :)

**Comment by jclausen** [comment] 2017-11-25 15:07
Looks like this is a regression from Issue #197, which re-appeared in the update to 2.0.6.  Any word on when a patch might be bumped?

**Comment by AdamSweeneyCreative** [comment] 2017-11-28 20:59
I too am having this problem. The tags in our app are lists of certifications, many of which include tags like "CPR Training" and will require uppercase tags. We'd love to use this component, so hopefully we'll see this bug fix soon.

**Comment by rickbolton** [comment] 2017-11-28 21:17
@AdamSweeneyCreative PR was merged the other day to fix this - https://github.com/shentao/vue-multiselect/pull/588. Just needs releasing to NPM

**Comment by wilga** [comment] 2017-11-29 22:42
I update to commit 06f5008 and checked the code for #588 was updated on my local install.  Still, the capitalized new tags are converted to lowercase in new tags.

**Comment by rickbolton** [comment] 2017-11-30 08:44
Hmm @wilga did you run `npm run bundle`. This will be done when @shentao updates the NPM as below are the differences when I run that on master. I guess I should PR to update these also since the changes..

<img width="1411" alt="screen shot 2017-11-30 at 08 42 42" src="https://user-images.githubusercontent.com/10371256/33421610-88ff2bf6-d5aa-11e7-8dc1-7c7cb109d943.png">

**Comment by rickbolton** [comment] 2017-11-30 08:51
PR created https://github.com/shentao/vue-multiselect/pull/598 @wilga to update the bundled files 👍

**Comment by shentao** [comment] 2017-11-30 11:20
Sorry about that. I know this is crucial for some of you and I’ve been neglecting the topic for too long. As you probably noticed, the repository changed owners. This is due to me changing my job and as you can imagine – a lot has been going on recently. I will release the fix today and hopefully be able to work some more on Multiselect on Sunday. 

Thank you for your patience!

**Comment by shentao** [comment] 2017-11-30 12:35
Fixed in 2.0.8.

**Closed** 2017-11-30 12:34 UTC
Labels: bug

**Comment by wilga** [comment] 2017-11-30 12:37
@rickbolton Thank you!

In my case, I'm using the Laravel framework.   Adding PR #598s commit (for the time being) to my package.json, updating and running `npm run dev`, all is fixed.

My package.json looks like this, as a temp fix:
'"vue-multiselect": "github:shentao/vue-multiselect#e86026f0d2b7a44d94da986cd7b80d54596c6358",'

**Comment by shentao** [comment] 2017-11-30 13:37
Happy to help. Sorry it took so long!
