### ISSUE TITLE
Can not render value with vue-multiselect, but console log work fine

### ISSUE THREAD

**Issue by deepak-nagar** [shentao/vue-multiselect#695] opened 2018-04-03 17:18 UTC

**Comment by shentao** [comment] 2018-04-03 17:19
Please make sure to follow the docs.
Closing because of the lack of any details or reproduction link.

**Closed by shentao** 2018-04-03 17:19 UTC

**Comment by deepak-nagar** [comment] 2018-04-03 17:25
i am not understand what are you saying

**Comment by shentao** [comment] 2018-04-03 17:33
Please provide a JSFiddle that shows what’s the problem or if that’s not possible, at least provide some more details, code snippets/errors. Without knowing what have you done that lead to the problem it’s not possible to help you. 

As stated in the issue template:
> Issues that don’t provide at least the basic problem description might be closed with any notice.

**Comment by deepak-nagar** [comment] 2018-04-03 17:34
![vuemultiple](https://user-images.githubusercontent.com/34958947/38265387-5b718030-3793-11e8-94cc-b97a29f4f0c0.png)
this is my app browser image

**Comment by deepak-nagar** [comment] 2018-04-03 17:35
![thirdvuemultiple](https://user-images.githubusercontent.com/34958947/38265413-74e27cae-3793-11e8-9b6a-ebb2bbfd9fe3.png)
this is my database table image

**Comment by deepak-nagar** [comment] 2018-04-03 17:36
![secondmulti](https://user-images.githubusercontent.com/34958947/38265439-8a4a8294-3793-11e8-9327-eb40caeb1467.png)
this is my code image Axios part

**Comment by deepak-nagar** [comment] 2018-04-03 17:38
![lastmu](https://user-images.githubusercontent.com/34958947/38265555-df55525a-3793-11e8-8e67-a585c96128e1.png)
this is my last image from code template part please help me

**Comment by shentao** [comment] 2018-04-03 17:43
I can’t see where the data that you fetched is passed to the multiselect. Your `:options` have the `specialization` value passed. The `v-model` points to `selectedSpecialization`.
However the data fetched is saved to `selectedDegrees`.

**Comment by deepak-nagar** [comment] 2018-04-03 17:44
sorry just updated please check again

**Comment by shentao** [comment] 2018-04-03 18:14
Sorry, I don’t know where the issue is. Try to make it work for a simpler case and then build it back into the async search as you have now.

**Comment by deepak-nagar** [comment] 2018-04-03 18:15
okay i am using other library thanks
