### ISSUE TITLE
FastClick conflict

### ISSUE THREAD

**Issue by xcheese** [shentao/vue-multiselect#686] opened 2018-03-23 03:09 UTC
if I use  
`FastClick.attach(document.body);`

I can not touch the Multiselect in mobile

**Comment by phil-r** [comment] 2018-04-20 17:09
duplicate of #159 

@xcheese check [fastclick docs](https://github.com/ftlabs/fastclick#fastclick) they recommend not to use it anymore as of 2015...

**Closed** 2018-07-29 13:43 UTC
Labels: bug, wontfix
