### ISSUE TITLE
Option for not showing on screen keyboard on mobile devices by default

### ISSUE THREAD

**Issue by yennor** [shentao/vue-multiselect#1298] opened 2020-07-07 16:34 UTC
On a mobile device the soft (on screen) keyboard opens by default when somebody clicks into the multiselect and it is searchable. Because of the limited screen on some displays, that is a really annoying behaviour.
It would be great if there is an option to disable that behaviour. The options displayed to the user are most of the times good enough and he only seldom needs to write an own text or filter them.
So when that option is set, the first time the user selects the multiselect, only the dropdown should open. And the second time the user taps into the input field it should get the focus and the keyboard appears.
It would be really cool if somebody would get that working and implement it as an option.

**Comment by rhaamo** [comment] 2020-11-16 09:45
Also to mention that (at least on iOS), hiding the keyboard does close the select dropdown, so having the keyboard eating half the screen is the only way to choose an item.

**Comment by akki-jat** [comment] 2022-11-08 16:47
Duplicate of https://github.com/shentao/vue-multiselect/issues/1467

**Closed by akki-jat** 2022-11-08 16:47 UTC
