### ISSUE TITLE
issue : deselect button add more items

### ISSUE THREAD

**Issue by maha-oueghlani** [shentao/vue-multiselect#1782] opened 2024-07-12 10:19 UTC
when I click on 'x' icons to deselect item, it not working and it add more items selected, you can find this on this screen video ,

this is my code : 

```
 <VueMultiselect
                            id="depends_on"
                            v-model="form.depends_on"
                            :options="permissionStore.permissions"
                            :close-on-select="true"
                            :clear-on-select="false"
                            placeholder="Select permissions"
                            select-label=""
                            :multiple="true"
                            label="name"
                            deselect-label=""
                        />
```

https://github.com/user-attachments/assets/2d4533d8-0167-46f1-a0af-d6501bdb8ce6

**Comment by logee48** [comment] 2024-07-19 06:58
assign it to me, i'll fix it

**Comment by am54ful** [comment] 2024-08-15 02:02
This is not a bug, already met this problem, need to assign the id or else will behave like yours

**Comment by mattelen** [comment] 2024-09-12 11:16
> This is not a bug, already met this problem, need to assign the id or else will behave like yours

Sounds like this is the solution (and it makes sense). Closing issue

**Closed by mattelen** 2024-09-12 11:16 UTC
