### ISSUE TITLE
slot "noResult" is not working

### ISSUE THREAD

**Issue by ravipatel2293** [shentao/vue-multiselect#978] opened 2019-05-13 05:15 UTC
hi,
When I'm using "noResult" slot with ":taggable: "true" then it's not showing the template inside the noResult slot.
I'm not sure why it's not working with taggable while in rest of the cases it works fine.

Can anyone have a workaround for this?

**Comment by kyrsquir** [comment] 2020-01-08 21:09
Is it showing default `List is empty` text?

If so, try using `noOptions` slot instead.

**Comment by sinau123** [comment] 2020-11-30 07:58
this issue still exists

@ravipatel2293  Have you solve this issue?

**Comment by ravipatel2293** [comment] 2020-11-30 08:03
As @kyrsquir said, i have used noOptions slot to achieve desired outcome.

**Comment by pasamsin** [comment] 2022-03-29 12:07
`<VueMultiselect v-model="departmans" :options="optionsdata" :multiple="true" group-values="libs" group-label="tumunusec" :group-select="true" placeholder="Type to search" track-by="isim" label="isim"><span slot="noResult">New text</span></VueMultiselect>`

this is not working.

<img width="851" alt="Ekran Resmi 2022-03-29 15 05 59" src="https://user-images.githubusercontent.com/25478013/160607528-a975f7c5-9a3b-4aa7-9ad3-59f202e7b694.png">

**Comment by Spliterr** [comment] 2022-07-07 00:41
I need to translate the content of "noResult" but it isnt working.

**Comment by CodeTappert** [comment] 2022-08-12 09:56
I have the same problem. The slots noResult and noOptions do not seem overridable.

**Comment by mattelen** [comment] 2022-08-19 13:53
It looks like the original issue of the noResult slot not working has been 'fixed' by using noOptions instead. 

@pasamsin To use a named slot, you will need to use a v-slot attribute, ideally on a template element, for example:
`
<VueMultiselect>
   <template v-slot:noResult>
      <span>New Text</span>
   </template>
</VueMultiselect>    
`
Feel free to check out this guide about how to use named slots: https://v2.vuejs.org/v2/guide/components-slots.html#Named-Slots

The other queries are a bit hard to troubleshoot and assist as there aren't many details to go on. I'm going to close this issue, but if anyone has more issues, feel free to open a new issue with a reproducible link - you can use this as a template: https://jsfiddle.net/mattelen/8cyt3hrn/3/

**Closed by mattelen** 2022-08-19 13:53 UTC
