### ISSUE TITLE
multiselect doesn't close automatically if wrapped in an HTML label tag

### ISSUE THREAD

**Issue by bacey** [shentao/vue-multiselect#507] opened 2017-09-15 15:46 UTC
https://jsfiddle.net/pqjww0me/60/

**Comment by shentao** [comment] 2017-09-18 15:20
Label triggers the focus event on its child – that’s why it doesn’t work.
I will look into it (maybe delaying the closing event might help).

Thanks for noticing!

**Closed** 2018-03-18 17:46 UTC
Labels: bug

**Comment by exoego** [comment] 2018-03-22 11:20
@shentao
Is this bug fixed in https://github.com/shentao/vue-multiselect/releases/tag/v2.1.0 ?
I am curious, since it is not mentioned in the release note

**Comment by shentao** [comment] 2018-03-26 14:07
@exoego I figured that this is not a bug. You can use labels that point to the `id` of Multiselect to trigger focus.

**Comment by yamsellem** [comment] 2019-01-10 10:42
@shentao may you please be more specific on how to resolve the jsfiddle issue?

Using `label for="something"` and `multiselect id="something"` won't fix this issue (as illustrated here: https://jsfiddle.net/4x5qdcyg/1/).

I've spend several hours to understand why pressing `enter` when overing a choice is working fine, and why clicking on the same choice, selects it, but do not close the select. I'm still stuck without a way to force the select to close.

Appart from this, my first impressions about multiselect are very great — so thanks a lot for this great library.

**Comment by elDub** [comment] 2019-01-10 13:42
@yamsellem You cannot nest the `multiselect` _within_ the `label` tag. Doing so makes the entire multiselect clickable at the HTML level and the label tag ends up receiving the event and placing focus back into the `mutiselect`. Using `for` and `id` is an _alternative_ to nesting.

**Comment by yamsellem** [comment] 2019-01-10 13:46
@elDub it's crystal clear: thanks! Maybe this can be added to the docs as a warning — it took me several hours to understand where the issue came from.

**Comment by elDub** [comment] 2019-01-10 13:50
@yamsellem I battled the same issue for quite a while thinking that I had implemented something wrong. It doesn't happen with native `select` tags from what I can tell, probably because the clients manage the situation.

**Comment by shentao** [comment] 2019-02-10 15:13
This shouldn’t be a problem in v3 since the component won’t open even if focused, instead you will have to press space or an arrow to open it, mimicking a native select.

**Comment by WofWca** [comment] 2019-11-08 04:23
[Native `<select>` tag can handle this](https://jsfiddle.net/1nyd6tug/).
I wouldn't call it not a bug.
