### ISSUE TITLE
./node_modules/vue-multiselect/dist/vue-multiselect.min.js mssing

### ISSUE THREAD

**Issue by Akku36** [shentao/vue-multiselect#1500] opened 2021-11-10 18:26 UTC
I've follow the documentation i found here : https://github.com/shentao/vue-multiselect/tree/next

### Steps to reproduce
Init a new vue 3 project with vue CLI, select Vue 3
Install the package : npm install vue-multiselect@next
Replace the current code you have in the Helloworld component by the one in the documentation

This is the result
![Capture](https://user-images.githubusercontent.com/75433524/141171470-e5b3f876-887c-4006-8e1e-c786fb5b38cb.PNG)

**Comment by mattelen** [comment] 2022-08-26 15:03
@Akku36 we've updated some of the documentation recently, so this might be fixed, but looks like the import reference might be incorrect in your code. If your import is targeting a specific file, and you don't need to, I recommending just importing the library without providing a path to a file, and it should work. 

I'm going to close this issue, but if this still isn't working, could you please provide a reproducible link/repo, that would be great!

**Closed by mattelen** 2022-08-26 15:03 UTC
