### ISSUE TITLE
i can't access to the documentation website

### ISSUE THREAD

**Issue by poldelgado** [shentao/vue-multiselect#1768] opened 2024-04-12 11:26 UTC
Hi guys, i've a problem accesing to   https://vue-multiselect.js.org/, i get a 404 from github pages.

![Captura de pantalla 2024-04-12 a las 8 25 40 a  m](https://github.com/shentao/vue-multiselect/assets/6215457/bc6ee939-a2a2-4e9b-88bf-b6ff66deab37)

**Comment by donnyv** [comment] 2024-04-12 16:03
Me too!

**Comment by mattelen** [comment] 2024-04-12 19:58
Duplicate of #1762, we're working on it

**Closed** 2024-04-12 19:58 UTC
