### ISSUE TITLE
Vue3 Composition API

### ISSUE THREAD

**Issue by diogofm7** [shentao/vue-multiselect#1643] opened 2023-01-08 20:54 UTC
I'm trying to use Multiselect with vue3, using composition API and I'm getting errors.

![image](https://user-images.githubusercontent.com/33474923/211218625-9e8ce34e-bb33-41a0-b037-c187a3467e2a.png)

![image](https://user-images.githubusercontent.com/33474923/211218602-78c55c8c-d9ce-470f-9c35-a9f80edb5407.png)

**Comment by mattelen** [comment] 2023-01-08 20:57
Can you confirm what version of the multiselect you are using? Only version 3 supports Vue 3

**Comment by diogofm7** [comment] 2023-01-08 21:07
> Você pode confirmar qual versão do multiselect você está usando? Apenas a versão 3 suporta Vue 3

npm install vue-multiselect@next

**Comment by diogofm7** [comment] 2023-01-08 21:30
![image](https://user-images.githubusercontent.com/33474923/211220070-b7a90bc1-635c-463f-9502-b53585302410.png)

Making some tweaks changed the error.

**Comment by cdroege** [comment] 2023-01-09 10:49
We saw similiar errors when migrating our codebase to Vue3. In our codebase, this was caused by defining `__VUE_OPTIONS_API__` as `false` (see the [Vue3 documentation](https://github.com/vuejs/core/blob/main/packages/vue/README.md#bundler-build-feature-flags) about this flag). When defining this as `true`, we could use `vue-multiselect` with the Composition API again.

This results in a small increase of the bundle size (about 2kb in our case).

@diogofm7 Did you also disable the Options API via this flag?

**Comment by akki-jat** [comment] 2023-01-29 07:21
@diogofm7 Please also provide reproducible repo link.

**Comment by AlyssonBarbosa** [comment] 2023-02-03 11:35
The same problem for me

**Comment by Wadhah-Sky** [comment] 2023-03-17 02:38
I managed to solve this issue by updating to:

`"vue-multiselect": "^3.0.0-beta.1"`

Run:

`npm install vue-multiselect@next --save`

Register the component and its style in :

**main.js**
```javascript

import 'vue-multiselect/dist/vue3-multiselect.css';
import {Multiselect} from 'vue-multiselect';

// Create vue App.
const app = createApp(App);

// Add component to app
app.component('multi-select', Multiselect);

```

Now, use the `<multi-select />` in your customized component, e.g. :

**MultiSelectComponent.vue**
```javascript

<template>

  <div>
    <multi-select v-model="value" :options="props.options" ></multi-select>
  </div>

</template>

<script>
/*
  Libraries, methods, variables and components imports
*/
import {ref, defineProps} from 'vue';

export default {
  name: "MultiSelectComponent"
}
</script>

<script setup>

/*
  Define handlers (properties, props and computed)
*/
const props = defineProps({
   options: {
     type: Array,
     required: true
   }
 });
const value = ref(null);

</script>

<style scoped>

.multiselect{
  width: 38vmin;
  font-size: 12px;
}

</style>

```

finally, you can import this customized component into your project views and provide list of options:

```javascript

<template>
  <div>
     <multi-select-component :options="[1,2,3]" />
  </div>
</template>

```

**Comment by wongyat88** [comment] 2023-10-13 07:00
Any luck to help? I am using vite and ts. I tried TS with same error. And I tried @Wadhah-Sky 's answer, still same error.
![image](https://github.com/shentao/vue-multiselect/assets/131446194/ea35600e-cdee-4994-82ea-21e50e3e0a5e)

**Comment by mattelen** [comment] 2024-12-31 11:43
Closing as fix to issue is making sure you have are running version 3 of the multiselect

**Closed by mattelen** 2024-12-31 11:43 UTC
Labels: needs repro
